import FWCore.ParameterSet.Config as cms

import copy
from HLTrigger.HLTfilters.hltHighLevel_cfi import *
vbfhzzllbbHLTFilter = copy.deepcopy(hltHighLevel)
# how to deal with multiple triggers:
# - True (OR) accept if ANY is true,
# - False (AND) accept if ALL are
vbfhzzllbbHLTFilter.andOr = cms.bool(True)
# provide list of HLT paths (or patterns) you want
vbfhzzllbbHLTFilter.HLTPaths = [
     'HLT_L1Jet15',   
     'HLT_Jet30',
     'HLT_Jet50',
     'HLT_Jet80',
     'HLT_DiJetAve15',
     'HLT_DiJetAve30',
     'HLT_DiJetAve50',
     'HLT_DiJetAve70',
     'HLT_DiJetAve130',
     'HLT_DiJetAve220',
     'HLT_TripleJet85',
     'HLT_QuadJet30',
     'HLT_QuadJet60',
     'HLT_SumET120',
     'HLT_L1MET20',
     'HLT_MET25',
     'HLT_IsoEle18_L1R',
     'HLT_IsoEle15_LW_L1I',
     'HLT_LooseIsoEle15_LW_L1R',
     'HLT_Ele10_SW_L1R',
     'HLT_Ele15_SW_L1R',
     'HLT_Ele15_LW_L1R',
     'HLT_DoubleIsoEle10_L1I',
     'HLT_DoubleIsoEle12_L1R',
     'HLT_DoubleIsoEle10_LW_L1I',
     'HLT_DoubleIsoEle12_LW_L1R',
     'HLT_DoubleEle5_SW_L1R',
     'HLT_DoubleEle10_LW_OnlyPixelM_L1R',
     'HLT_DoubleEle10_Z',
     'HLT_DoubleEle6_Exclusive',
     'HLT_Photon15_L1R',
     'HLT_Photon25_L1R',
     'HLT_L1Mu',
     'HLT_L1MuOpen',
     'HLT_L2Mu9',
     'HLT_IsoMu9',
     'HLT_IsoMu11',
     'HLT_IsoMu13',
     'HLT_IsoMu15', 
     'HLT_Mu3',
     'HLT_Mu5',
     'HLT_Mu7',
     'HLT_Mu9',
     'HLT_Mu11',
     'HLT_Mu13',
     'HLT_Mu15',
     'HLT_Mu15_Vtx2mm',
     'HLT_DoubleIsoMu3',
     'HLT_DoubleMu3',
     'HLT_DoubleMu3_Vtx2mm',
     'HLT_DoubleMu7_Z',
     'HLT_BTagIP_Jet180',
     'HLT_BTagIP_Jet120_Relaxed',
     'HLT_BTagIP_DoubleJet120',
     'HLT_BTagIP_DoubleJet60_Relaxed',
     'HLT_BTagIP_TripleJet70',
     'HLT_BTagIP_TripleJet40_Relaxed',
     'HLT_BTagIP_QuadJet40',
     'HLT_BTagMu_DoubleJet60_Relaxed',
     'HLT_BTagMu_TripleJet70',
     'HLT_BTagMu_TripleJet40_Relaxed',
     'HLT_BTagMu_QuadJet40',
     'HLT_BTagMu_QuadJet30_Relaxed',
     'HLT_BTagMu_HT370',
     'HLT_DoubleLooseIsoTau',
     'HLT_IsoEle8_IsoMu7',
     'HLT_IsoEle10_Mu10_L1R',
     'HLT_IsoEle10_BTagIP_Jet35',
     'HLT_IsoEle12_Jet40',
     'HLT_IsoEle12_DoubleJet80',
     'HLT_IsoEle5_TripleJet30',
     'HLT_IsoEle12_TripleJet60',
     'HLT_IsoEle12_QuadJet35',
     'HLT_IsoMu7_BTagIP_Jet35',
     'HLT_IsoMu7_BTagMu_Jet20',
     'HLT_IsoMu7_Jet40',
     'HLT_NoL2IsoMu8_Jet40',
     'HLT_Mu14_Jet50',
     'HLT_Mu5_TripleJet30'
#                               'HLT_IsoMu11', 
#				'HLT_Mu15_L1Mu7',
#       			'HLT_Mu15', 
#       			'HLT_DoubleMu3', 
#       			'HLT_IsoEle15_L1I', 
#       			'HLT_IsoEle18_L1R', 
#       			'HLT_DoubleIsoEle10_L1I', 
#				'HLT_DoubleIsoEle12_L1R'
     ]
